# Generated by Django 2.2.7 on 2020-03-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCU_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=100)),
                ('message_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_member', models.CharField(max_length=150)),
                ('project_detail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('year', models.DecimalField(decimal_places=2, max_digits=4)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModelTest',
        ),
    ]
