# Generated by Django 2.2.7 on 2020-03-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCU_App', '0002_auto_20200309_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
